image: node:latest
stages:
  - build
  - deploy
cache:
  paths:
  - node_modules/
build:
  stage: build
  script:
  - npm i
  - npm run build
  artifacts:
    paths:
    - node_modules/
    - build/
deploy:
  stage: deploy
  script:
  - ssh-keygen -R $SERVER_IP
  - mkdir ~/.ssh && cd ~/.ssh && touch server && echo $SERVER_KEY >> server
  - scp -P $SERVER_PORT -r -i ~/.ssh/server build/* $SERVER_USER@$SERVER_IP:/var/www/hazratgs.com
