image: node:latest
stages:
  - deploy
deploy:
  stage: deploy
  before_script:
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - cd ~/.ssh
  - touch server
  - chmod 600 server
  - echo "$KEY" >> server
  script:
  - npm i
  - npm run build
  - scp -vrp -o stricthostkeychecking=no -P $PORT -i ~/.ssh/server build/* $USER@$HOST:/var/www/hazratgs.com
