image: node:latest
stages:
  - build
  - deploy
cache:
  paths:
  - node_modules/
build:
  stage: build
  script:
  - npm i
  - npm run build
  artifacts:
    paths:
    - node_modules/
    - build/
deploy:
  stage: deploy
  script:
  - mkdir ~/.ssh && chmod 700 ~/.ssh
  - cd ~/.ssh && touch server && chmod 600 server && echo $KEY >> server
  - ssh -oStrictHostKeyChecking=no -P $PORT -r -i ~/.ssh/server $USER@$HOST
